//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTask1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class course_student
    {
        public int id { get; set; }
        [DisplayName("Student Name")]
        public Nullable<int> Student_id { get; set; }
        [DisplayName("Course Name")]
        public Nullable<int> Course_id { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
