//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayTask1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.course_student = new HashSet<course_student>();
        }
    
        public int id { get; set; }
        [DisplayName("Student Name")]
        public string Name { get; set; }
        public int Age { get; set; }
        [DisplayName("Year")]
        public int student_course { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_student> course_student { get; set; }
    }
}
