//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testlogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Productid { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> UnitsinStock { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
