//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dayTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string First_Name { get; set; }
        public string Last_name { get; set; }
        public string E_mail { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public string Job_Title { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string picture { get; set; }
        public string CV { get; set; }
    }
}
