//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dayTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        public int Orderid { get; set; }

        public int Customerid { get; set; }
        [DisplayName("Order Date")]
        public Nullable<System.DateTime> Orderdate { get; set; }
        [DisplayName("Customer Name")]
        public virtual Employee Employee { get; set; }
    }
}
